name: Daily Blocklist Update

on:
  schedule:
    - cron: '0 16 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Aktualisiert auf v4 (schneller)

      - name: Set up Python
        uses: actions/setup-python@v5 # Aktualisiert auf v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Optimizer Script
        run: python merge.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Das hier ist der "Wachmacher" fÃ¼r deinen alten Code:
          echo "Last Update: $(date +'%Y-%m-%d %H:%M')" > version.txt
          
          git add sources.txt blocklist.txt version.txt
          git commit -m "Daily Update: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push