name: Daily Blocklist Update

on:
  schedule:
    # 03:37 Uhr UTC ist weniger ausgelastet als 03:00 Uhr
    - cron: '0 6 * * *' 
  workflow_dispatch: # Erlaubt manuellen Start

permissions:
  contents: write # WICHTIG: Erlaubt das Schreiben/Pushing der Änderungen

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Optimizer Script
        # Das -u sorgt dafür, dass die Prints sofort im Log erscheinen
        run: python -u merge.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Der Wachmacher: Wir schreiben das aktuelle Datum in eine version.txt
          echo "Last Update: $(date +'%Y-%m-%d %H:%M')" > version.txt
          
          git add sources.txt blocklist.txt version.txt
          
          # Wir commiten immer, da sich die version.txt ja auf jeden Fall geändert hat
          git commit -m "Daily Update: $(date +'%Y-%m-%d %H:%M')"
          git push